language: node_js
node_js:
- '4.1'
before_install:
- npm install -g tsd
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: iisLOTezvVMILgG4pGa1c+RxIk7BdxDTMY4h1QiYkU637w7djVt19/xemDFBtrSWar58VW41IW5ES2gi0ZnCeVI94mMCTNJHOwMWoCX22tkO12IRXTts/B5glE+r8GZt7a7U9K0pV7bBvkPSH9YQ7lla9KJ7oV6yg5zcGSJ7CGgKZ7DVKcd3OHEvqAwdijJ/rkWwSpWWZ20X/mxKyizlP4LCfN77cs3rzKMmNWggm3lczoHAllY5mid/Zrk7/czNRwW/E3FK9rdmheQfTPHzrEml+EqvKFDILPxO4AcJL8iQh2q6ZIFJiJHR37y9Q5N+t0mNQaQOAZrvL2R8outyvkm6/xMX3YEaxoQZPzjqj80PF/nUcYWmP44j71a9yZeM9zMbLEfeUwOZi/3DeFpoX9+26qD7NxSRvqNaXnGIO3Y3KT/3O0IH51+lxwsuqG8o43IsSZoYfN03gMWVlF0pN3U6jZd9WB9ZWHzsb2DQ6x1Q5xZx7i4gngq1fHkHAdFiFVCl/gjPkAZRc6A+YfbZYxv8jFWWwbm99SO8MPrWOR1Hm++jGzndmt7Z3YfuyPcV/xBM+uUyjjdLbY+iYPCZMj31TgP2QKobHykqfWYI/uljHTe3zGmPSuyryLdyMkNIgaGvTruyIJjZo9KmektgeKaAHjT+7BLi8oe1fI/Zs0U=
  on:
    tags: true
    repo: pushrocks/gulp-inspect
notifications:
  slack:
    secure: f5Uss0z9RPl/QcA/DroB8loyE93aOYI6bqCkrsiUscmZtlv/TVQtT4dxqGA6uvcG6iTQDBi3Ul88dQxWkRm4IqbhY35/iMaV2dHW4FVYMAh8GQMbsfL2sALCcufxD9blw47awv3iFcwhV1EeyesscjgL0JIjduk96v/7G/6QIO2838M1lzlgtj+kRUkim8qkaEs1je3gRrhMUIjLuAdscMXyUKYFMjWo9ACSjVUl30R/ZNemb18itIja6i92GotreBgcfEMczvy58ovDC7xdJUsY8LjMI01DwY+WPRnI0tAhsuI8moBwwcdM4e3bAjKjucQRjO33O5bMWRZ6QCiYd0DnCEFyCPQLJ4GSy/tkD00n8ijLHAOSV3AH1zNbdK1EAdSPQXDvlI36KJn/2hyQLoitGHVUPr76ujJWP82ypO2tgIp3XQU0dJVCxDuHnwJO2+hjdI+gCPqxNTpjeujHx3UdkTGNRjuuf9dlZ/D08fApjYxy2fxItTqo3QjP/nrqvBXUOPP8yPHpjIT4H2t5Pr4SJjBGI6X4qhKyFj6s9rA/Xu1rL+45zu1C3uC3z+u3T9UwrbzJ/cZM6r6UQvQmUvIfBNaMlg4I/diQCDIPL+Rhop2nylY3IcHmJnk2itn7kOqj1tohCpFEml5pRuSZy4udWywkdtyBAsHWFLF7oiQ=
